import LayoutComponent from "src/components/Layout";
import "./globals.css";
import React from "react";
import { Nunito } from "next/font/google";
import { IUser } from "src/types";
import { cookies } from "next/headers";

export const metadata = {
  title: "Matias Benitez Blog",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
});

interface props {
  children: React.ReactNode;
  params: { locale: "en" | "es" | "jp" };
}

export default async function RootLayout({
  children,
  params: { locale },
}: props) {
  const cookieStore = cookies();
  const cookiesObj = {
    current_user: cookieStore.get("current_user"),
    token: cookieStore.get("token"),
    selectedLanguage: cookieStore.get("selected_language"),
  };

  const currentUser: IUser | undefined =
      cookiesObj.current_user && cookiesObj.current_user.value !== ""
        ? JSON.parse(cookiesObj.current_user.value)
        : undefined,
    token =
      cookiesObj.token && cookiesObj.token.value !== ""
        ? cookiesObj.token.value
        : undefined;

  const isLoggedIn = currentUser && token ? true : false;

  return (
    <html
      lang={locale}
      data-theme="autumn"
      className={nunito.className + " antialiased"}
    >
      <body>
        <LayoutComponent isLoggedIn={isLoggedIn}>{children}</LayoutComponent>
      </body>
    </html>
  );
}
